const alpine = [
    'This tiny egg is rather light.$e2.png',
    'This light egg is floating in the air.$e5.png',
    'This egg has a faint green glow around it.$e8.png',
    'This egg has a pleasant, musky smell.$e9.png',
    'It’s almost like time is distorted around this egg.$e11.png',
    'This crystalline egg almost looks like you could reach into its depths.$e12.png',
    'Wind gusts around this egg.$e13.png',
    'You can see the baby dragon curled up inside this translucent egg.$e14.png',
    'This glossy green egg is rather warm.$e15.png',
    'This egg shines brilliantly in moonlight, and is covered in red spots.$e23.png',
    'This egg is covered in thick blue stripes.$e24.png',
    'This egg has a striking pattern.$e26.png',
    'This egg is covered in pale blue spots.$e27.png',
    'This egg is unusually large and heavy.$e30.png',
    'This egg makes you feel a bit uneasy.$e34.png',
    'This translucent egg shines like starlight.$e35.png',
    'This egg is soft and smells uncannily like cheese.$e36.png',
    'This egg is much smaller than the others.$e37.png',
    'This egg is so tiny you almost didn’t see it.$e39.png',
    'This egg gleams with a reddish shine.$e41.png',
    'This egg shines coldly in the moonlight.$e45.png',
    'This egg shines like a diamond.$e50.png',
    'This egg can’t seem to make up its mind what color it is.$e52.png',
    // 'Electric sparks dance across the surface of this egg.$e53_20210508.png',
    'Bright sparks glide across the surface of this egg’s shell.$e53.png',
    'This mottled egg looks positively ancient.$e56.png',
    'It’s bright. And pink.$e62.png',
    'This shiny egg smells faintly like flowers.$e64.png',
    'Frost is creeping over this cold egg.$e66.png',
    'This egg is heavy and rough, as if it were made out of rock.$e70.png',
    'This egg is very reflective, almost metallic-looking.$e74.png',
    'This heavy egg feels slightly warm.$e78.png',
    'This egg has icicles forming on it.$e87.png',
    'This egg is hidden in the trees.$e88.png',
    'This egg is smooth and shiny.$e89.png',
    'This shiny egg gives off an almost magical aura.$e90.png',
    'This tiny cobalt egg has a crystalline sheen.$e92.png',
    'This egg shines brightly in the sunlight.$e96.png',
    'This metallic egg shows faint iridescence in moonlight.$e98.gif',
    'This small egg is engulfed in a cool, purple flame.$e99.png',
    'This egg has an orange aura radiating from it.$e100.png',
    'This egg is hidden behind the others, as if it is shy.$e105.png',
    'This egg glows with a brilliant radiance.$e110.png',
    'This dense, crystalline egg seems dangerously unstable.$e112.png',
    'This dull purple egg has two bright stripes on it.$e113.png',
    'This tiny egg is heavier than you expected.$e114.png',
    'This egg appears to be made of limestone.$e115.png',
    'This egg is tiny and made out of several pieces of paper folded together.$e117.png',
    'This egg has a velvety texture.$e118.png',
    'This little egg is soft with a few feathers stuck to it.$e119.png',
    'Wow, purple isn’t a color of egg you expected to see.$e121.png',
    'This egg feels like polished stone.$e122.png',
    'This blue and bronze egg piques your curiosity.$e126.png',
    'A cool mountain breeze blows around this egg.$e130.gif',
    'This egg radiates an otherworldly chill.$e131.png',
    'This egg shines in the moonlight.$e132.png',
    'This egg looks like a beautiful blue stone.$e134.png',
    'The markings on this egg match the weather outside.$e137.gif',
    'This egg gives off a beautiful glow.$e140.png',
    'This egg seems to be glowing in spots.$e142.png',
    'This egg glows from within.$e146.png',
    'This egg has a rough—yet shiny—shell.$e144.png',
    'This egg is surrounded by fog.$e150.png',
    'This egg is glowing as brightly as the sun.$e152.png',
    'This brown egg is covered in intricate designs.$e159.png',
    'This egg is split down the middle into two colors.$e162.png',
    // 'This opalescent egg shimmers in the moonlight.$e163_20210508.png',
    'This opalescent egg shimmers in the moonlight.$e163.png',
    'There is a thin layer of moisture coating this egg.$e165.png',
    'This egg has a very clean look; it’s completely devoid of dirt and scratches.$e171.png',
    'Mana courses throughout this glassy egg.$e172.gif',
    'This shiny egg seems to radiate power.$e179.png',
    'This egg shimmers like gold.$e187.png',
    'This icy egg sparkles with frost.$e193.png',
    'This egg is very large, but light for its size.$e194.png',
    'An aura of serenity surrounds this iridescent egg.$e195.png',
    'The brilliant blue spots on this egg stand out.$e197.png',
    'This tiny egg resembles a seed.$e198.png',
    'This shimmering egg was hidden far from the others.$e199.png',
    'This soft egg is carefully nestled in feathers and snow.$e201.png',
    'Mana flows like a current through this glassy egg.$e208.png',
    'Starlight shimmers across this egg’s iridescent shell.$e209.png',
    'This egg reminds you of the night sky.$e211.png',
    'This plain blue egg almost seems to float.$e212.png',
    'This egg shakes slightly when taken out of the light.$e214.png',
    'It feels like this egg knew you were coming.$e222.png',
    'This striped egg has a rough, ridged texture.$e224.png',
    'This egg emanates a peculiar smell.$e226.png',
    'This tiny egg flashes in the sunlight.$e227.png',
    'This tiny white egg shakes sometimes.$e228.png',
    'Cold lightning arcs out from this egg’s shell if you try to touch it.$dc_16th_birthday_1.png',
    'This tiny blue egg gives you a slight shock when you touch it.$e_202207_1.png',
    'This scaled egg is surrounded by the others.$e_202207_6.png',
    'Two thin stripes crisscross the shell of this egg.$e_202209_2.png',
    'This egg glows with the light of the moon.$e_202304_1_1.png',
    'Crystals are growing around the shell of this little egg.$dc_17th_birthday_1.png',
    'This egg glows vibrantly in the dark.$dc_17th_birthday_2.png',
    'A red stone is embedded in this egg’s cold shell.$dc_17th_birthday_3.png',
    'This smooth egg has dark markings.$e_202306_1_3.gif',
    'Delicate petals envelop this egg.$e_202307_1_2.png',
    'Something about this heavy egg unnerves you.$e_202308_2.png',
    'It is difficult to discern this egg from its gloomy surroundings.$e_202310_2.png',
    'This speckled egg has deep blue spots.$e_202403_1.png',
    'This egg seems lonely sitting by itself.$e_202404_1.png',
    'This egg is covered in black and white stripes.$dc_18th_birthday_1.png',
    'This dark egg has a delicate shell that smells faintly of pine.$e_202406_1.png',
    'This egg’s glittering shell sometimes gets lost in fog.$e_202407_2.png',
    'This egg was left in an ornate nest of fur and grass.$e_202408_1.png',
    'This egg reverberates with a sound that is somehow haunting and soothing at once.$20250521_phantasma_egg.png',
    'This egg’s shell has thin bands of vivid color.$20250629_lunate_egg.png',
];
const coast = [
    'This drab egg rests far from the water’s edge.$e1.png',
    'This tiny egg is rather light.$e2.png',
    'This heavy egg has a soft, yielding shell.$e3.png',
    'This light egg is floating in the air.$e5.png',
    'This egg has raised golden ridges.$e6.png',
    'This egg has a black cap.$e7.png',
    'This egg has a faint green glow around it.$e8.png',
    'This egg has a pleasant, musky smell.$e9.png',
    'This egg is off-white in color and smells a bit like salt.$e10.png',
    'This egg smells faintly like brine.$e25.png',
    'This mottled red egg almost glows from within.$e31.png',
    'This egg makes you feel a bit uneasy.$e34.png',
    'This translucent egg shines like starlight.$e35.png',
    'This egg is soft and smells uncannily like cheese.$e36.png',
    'This egg is much smaller than the others.$e37.png',
    'This egg reminds you of the sea.$e38.png',
    'This egg gleams with a reddish shine.$e42.png',
    'This egg shines coldly in the moonlight.$e45.png',
    'This egg is sitting on a cloud.$e47.png',
    'This egg appears to be covered in scales.$e49.png',
    'This egg can’t seem to make up its mind what color it is.$e52.png',
    'This mottled egg looks positively ancient.$e56.png',
    'It’s bright. And pink.$e61.png',
    'This striped egg feels moist.$e72.png',
    'This egg is very reflective, almost metallic-looking.$e74.png',
    'This egg is covered in tiny golden scales.$e80.png',
    'This egg has strange markings on it.$e85.png',
    'This egg is hidden in the trees.$e88.png',
    'This shiny egg gives off an almost magical aura.$e90.png',
    'This tiny, dark egg fills you with existential dread.$e91.png',
    'This tiny cobalt egg has a crystalline sheen.$e92.png',
    'This green and silver egg lurks in the shadows, tempting you to steal it.$e93.png',
    'This egg shines brightly in the sunlight.$e96.png',
    'This egg has an orange aura radiating from it.$e100.png',
    'This tiny egg smells like the sea.$e102.png',
    'This egg is hidden behind the others, as if it is shy.$e105.png',
    'This egg is tiny and made out of several pieces of paper folded together.$e117.png',
    'This little egg is soft with a few feathers stuck to it.$e119.png',
    'Wow, purple isn’t a color of egg you expected to see.$e121.png',
    'This egg feels like polished stone.$e124.png',
    // 'This egg is wet from the waves and has bright red stripes.$e128_20210508.png',
    'This egg has vivid red stripes, reminiscent of waves and flames at once.$e128.png',
    'This egg radiates an otherworldly chill.$e131.png',
    'This egg looks like a beautiful blue stone.$e134.png',
    // 'This tiny egg shines like a pearl.$e138_20210508.png',
    'This tiny egg shines like a pearl.$e138.png',
    'This egg gives off a beautiful glow.$e140.png',
    'This striped egg has a warm glow.$e141.png',
    'This egg seems to be glowing in spots.$e142.png',
    'This egg is surrounded by fog.$e150.png',
    'This egg has faint markings.$e157.png',
    'This egg is rocking back and forth in a puddle, creating small waves.$e160.png',
    'This egg is split down the middle into two colors.$e162.png',
    'This egg is sitting in a shallow puddle.$e167.png',
    'This egg seems to be floating on a puddle.$e168.png',
    'This egg is slimy and blue.$e169.png',
    'This egg has a very clean look; it’s completely devoid of dirt and scratches.$e171.png',
    'Mana courses throughout this glassy egg.$e177.gif',
    'This shiny egg seems to radiate power.$e180.png',
    'Water glistens on this egg’s shimmering shell.$e188.png',
    'This tiny egg is striped and feels coarse.$e189.png',
    'The vibrant scales on this egg glisten in the sunlight.$e192.png',
    'The brilliant blue spots on this egg stand out.$e197.png',
    'This tiny egg resembles a seed.$e198.png',
    'This shimmering egg was hidden far from the others.$e199.png',
    'This egg’s shell is slippery and clean.$e200.png',
    'Mana flows like a current through this glassy egg.$e208.png',
    'This plain blue egg almost seems to float.$e212.png',
    'You hear a soft melody as you approach this egg.$e213.png',
    'Something about this egg seems to lure you in.$e215.png',
    'This striped egg is surprisingly heavy.$e217.png',
    'It feels like this egg knew you were coming.$e222.png',
    'This tiny egg flashes in the sunlight.$e227.png',
    'This tiny white egg shakes sometimes.$e228.png',
    'This scaly egg seems to disappear in the depths.$e230.png',
    'This shady egg seems to be lurking just out of sight.$dc_16th_birthday_2.png',
    'This tiny blue egg gives you a slight shock when you touch it.$e_202207_1.png',
    'This scaled egg is surrounded by the others.$e_202207_2.png',
    'A single blue spot marks this egg.$e_202208_1.png',
    'This little egg blends into the sand.$e_202209_1.png',
    'Two thin stripes crisscross the shell of this egg.$e_202209_2.png',
    'This egg glows with the light of the moon.$e_202304_1_1.png',
    'A red stone is embedded in this egg’s cold shell.$dc_17th_birthday_3.png',
    'This egg has washed up on the beach.$dc_17th_birthday_4.png',
    'This smooth egg has dark markings.$e_202306_1_3.gif',
    'Delicate petals envelop this egg.$e_202307_1_2.png',
    'This egg is well-camouflaged.$e_202308_1.png',
    'Something about this heavy egg unnerves you.$e_202308_2.png',
    'This egg seems lonely sitting by itself.$e_202404_1.png',
    'This beautifully patterned egg was buried close to shore.$dc_18th_birthday_2.png',
    'This heavy egg has a distinct scorched smell.$e_202406_3.png',
    'Three bold red stripes cut across this egg’s shell.$e_202409_1.png',
    'This egg washed ashore.$e_202503_2.png',
    'This tiny egg is leathery and damp.$202504_trion_egg.png',
    'It’s a tiny speckled egg.$20250521_impish_egg.png',
    'Sparks dance beneath the translucent surface of this dark egg.$20250727_missinic_egg.png',
];
const desert = [
    'This tiny egg is rather light.$e2.png',
    'This egg has a faint green glow around it.$e8.png',
    'This egg has a pleasant, musky smell.$e9.png',
    'This delicately patterned egg is sitting in the sunshine.$e16.png',
    'This egg is surrounded by mysterious, reflective dust.$e17.png',
    'This egg has a faintly exotic scent.$e21.png',
    'This egg is dark with light speckles...or maybe it’s light with dark speckles?$e22.png',
    'This egg smells rather rancid.$e29.png',
    'This egg makes you feel a bit uneasy.$e34.png',
    'This translucent egg shines like starlight.$e35.png',
    'This egg is soft and smells uncannily like cheese.$e36.png',
    'This egg is much smaller than the others.$e37.png',
    'This egg gleams with a reddish shine.$e40.png',
    'This egg shines coldly in the moonlight.$e45.png',
    'This egg can’t seem to make up its mind what color it is.$e52.png',
    'This mottled egg looks positively ancient.$e56.png',
    'It’s bright. And pink.$e62.png',
    'This egg is yellow with orange speckling.$e65.png',
    'This shiny egg gives you a headache when you get close.$e68.png',
    'This egg is heavy and rough, as if it were made out of rock.$e70.png',
    'This egg is very reflective, almost metallic-looking.$e74.png',
    'The surface of this egg is rough and sharp.$e81.png',
    'This egg is hidden in the trees.$e88.png',
    'This egg is smooth and shiny.$e89.png',
    'This shiny egg gives off an almost magical aura.$e90.png',
    'This tiny cobalt egg has a crystalline sheen.$e92.png',
    'This egg shines brightly in the sunlight.$e96.png',
    'This metallic egg shows faint iridescence in moonlight.$e98.gif',
    'This egg has an orange aura radiating from it.$e100.png',
    'This egg is buried in leaf litter.$e107.png',
    'This egg resembles a glowing stone.$e108.gif',
    'This egg glows with a brilliant radiance.$e110.png',
    'This egg is tiny and made out of several pieces of paper folded together.$e117.png',
    'This little egg is soft with a few feathers stuck to it.$e119.png',
    'Wow, purple isn’t a color of egg you expected to see.$e121.png',
    'This egg is rather warm.$e127.png',
    'This tiny egg has a bold red streak on it.$e129.png',
    'This egg radiates an otherworldly chill.$e131.png',
    'This egg looks like a beautiful blue stone.$e134.png',
    'This egg seems quite harmless.$e135.png',
    'This egg gives off a beautiful glow.$e140.png',
    'This light egg has very vibrant colors.$e143.png',
    'This glassy egg has a single stripe on it.$e145.gif',
    'This egg has brightly colored markings on it.$e147.png',
    'This egg is surrounded by fog.$e150.png',
    'A delicate web-like pattern decorates this egg’s shell.$e155.png',
    // Thunder dragon (e158): Keep both descriptions
    'Whenever you go near this egg your hair stands on end.$e158.png',
    'Whenever you go near this egg, your hair stands on end.$e158.png',
    'This egg smells strongly of turpentine.$e161.png',
    'This egg is split down the middle into two colors.$e162.png',
    'This egg has a very clean look; it’s completely devoid of dirt and scratches.$e171.png',
    'Mana courses throughout this glassy egg.$e175.gif',
    'The air shimmers around this egg, as if from heat.$e178.png',
    'This shiny egg seems to radiate power.$e181.png',
    'This egg was buried in a sand dune.$e191.png',
    'This egg is very large, but light for its size.$e194.png',
    'The brilliant blue spots on this egg stand out.$e197.png',
    'This tiny egg resembles a seed.$e198.png',
    'This shimmering egg was hidden far from the others.$e199.png',
    'Mana flows like a current through this glassy egg.$e208.png',
    'It almost looks like there are claw marks on this egg.$e210.png',
    'This shiny gray egg smells of burnt metal.$e218.png',
    'This egg has a winding pattern on it.$e223.png',
    'This striped egg has a rough, ridged texture.$e224.png',
    'This tiny egg flashes in the sunlight.$e227.png',
    'This tiny white egg shakes sometimes.$e228.png',
    'Grabbing this tiny egg makes you feel reckless.$dc_16th_birthday_3.png',
    'This tiny blue egg gives you a slight shock when you touch it.$e_202207_1.png',
    'This scaled egg is surrounded by the others.$e_202207_3.png',
    'Two thin stripes crisscross the shell of this egg.$e_202209_2.png',
    'This egg glows with the light of the moon.$e_202304_1_1.png',
    'A red stone is embedded in this egg’s cold shell.$dc_17th_birthday_3.png',
    'A low hum emanates from this rough egg.$dc_17th_birthday_5.png',
    'This smooth egg has dark markings.$e_202306_1_3.gif',
    'Delicate petals envelop this egg.$e_202307_1_1.png',
    'This egg is well-camouflaged.$e_202308_1.png',
    'Something about this heavy egg unnerves you.$e_202308_2.png',
    'This speckled egg has deep blue spots.$e_202403_1.png',
    'This egg seems lonely sitting by itself.$e_202404_1.png',
    'This egg’s glittering shell sometimes gets lost in fog.$e_202407_2.png',
    'This egg has a rough, scaly surface.$202504_aardrake_egg.png',
    'This surface of this egg is covered in pits and craters.$20250521_luna_egg.png',
    'This egg has a fiery pattern.$20250727_flameback_egg.png',
];
const forest = [
    'This tiny egg is rather light.$e2.png',
    'This heavy egg has a soft, yielding shell.$e4.png',
    'This light egg is floating in the air.$e5.png',
    'This egg has a faint green glow around it.$e8.png',
    'This egg has a pleasant, musky smell.$e9.png',
    'It’s almost like time is distorted around this egg.$e11.png',
    'You can see the baby dragon curled up inside this translucent egg.$e14.png',
    'This glossy green egg is rather warm.$e15.png',
    'This delicately patterned egg is sitting in the sunshine.$e16.png',
    'This ashen egg is smooth to the touch.$e19.png',
    'This large egg has a lustrous sheen and appears to be covered in scales.$e20.png',
    'This egg is dark with light speckles...or maybe it’s light with dark speckles?$e22.png',
    'This egg has a striking pattern.$e26.png',
    'This egg makes you feel a bit uneasy.$e34.png',
    'This translucent egg shines like starlight.$e35.png',
    'This egg is soft and smells uncannily like cheese.$e36.png',
    'This egg is much smaller than the others.$e37.png',
    'This egg is so tiny you almost didn’t see it.$e39.png',
    'This egg gleams with a reddish shine.$e41.png',
    'This egg is sitting in a patch of grass and small flowers even though there’s no sun in the cave.$e44.png',
    'This egg shines coldly in the moonlight.$e45.png',
    // 'This tiny egg is mysterious and dark.$e46_20210508.png',
    'This tiny egg is mysterious and dark.$e46.png',
    'This egg is sitting on a cloud.$e47.png',
    // 'This egg displays the colors of both dawn and dusk.$e48_20210508.png',
    'This egg displays the colors of both dawn and dusk.$e48.png',
    'This egg can’t seem to make up its mind what color it is.$e52.png',
    'This mottled egg looks positively ancient.$e56.png',
    'It’s bright. And pink.$e62.png',
    'This shiny egg smells faintly like flowers.$e63.png',
    'This tiny egg gives off a colorful glow.$e73.png',
    'This egg is very reflective, almost metallic-looking.$e74.png',
    'This egg is speckled with rosette-like markings.$e75.png',
    'This egg is sitting in a pile of small pebbles.$e76.png',
    'This heavy egg feels slightly warm.$e78.png',
    'This egg is covered in tiny golden scales.$e80.png',
    'This egg has strange markings on it.$e84.png',
    'This egg is hidden in the trees.$e88.png',
    'This shiny egg gives off an almost magical aura.$e90.png',
    'This tiny cobalt egg has a crystalline sheen.$e92.png',
    'This egg shines brightly in the sunlight.$e96.png',
    'The markings on this egg glow brightly in the shadows.$e97.png',
    'This egg has an orange aura radiating from it.$e100.png',
    'This heavy egg has an earthy scent, like freshly-tilled soil.$e103.png',
    'This tiny glowing egg tempts you to follow its light.$e104.png',
    'This egg is hidden behind the others, as if it is shy.$e105.png',
    'This egg is buried in leaf litter.$e107.png',
    'This egg appears to be made of limestone.$e115.png',
    'This egg smells musty, like rotting leaves.$e116.png',
    'This egg is tiny and made out of several pieces of paper folded together.$e117.png',
    'This little egg is soft with a few feathers stuck to it.$e119.png',
    'This massive egg is covered with thick plates.$e120.png',
    'Wow, purple isn’t a color of egg you expected to see.$e121.png',
    'This tiny egg has a bold red streak on it.$e129.png',
    'This egg radiates an otherworldly chill.$e131.png',
    'This egg looks like a beautiful blue stone.$e134.png',
    'The markings on this egg match the weather outside.$e137.gif',
    'This egg gives off a beautiful glow.$e140.png',
    'This egg seems to be glowing in spots.$e142.png',
    'This egg glows from within.$e146.png',
    'This egg has brightly colored markings on it.$e148.gif',
    'This egg is covered in bright spots.$e149.png',
    'This egg is surrounded by fog.$e150.png',
    'A small puddle of condensation has collected under this egg.$e151.png',
    'This egg has a very thin shell.$e154.png',
    'This egg is a lush green hue.$e156.gif',
    'This egg is split down the middle into two colors.$e162.png',
    // 'This opalescent egg shimmers in the moonlight.$e164_20210508.png',
    'This opalescent egg shimmers in the moonlight.$e164.png',
    'There is a thin layer of moisture coating this egg.$e165.png',
    'This smooth green egg looks vaguely familiar.$e166.png',
    'This egg seems to be floating on a puddle.$e168.png',
    'This egg shakes from time to time, as if it is eager to hatch.$e170.png',
    'This egg has a very clean look; it’s completely devoid of dirt and scratches.$e171.png',
    'Mana courses throughout this glassy egg.$e173.gif',
    'This shiny egg seems to radiate power.$e182.png',
    'This egg has a rough shell.$e185.png',
    'This ashen egg is smooth to the touch.$e19.png',
    'Oh my. There is a Leetle Tree among the eggs.$Leetle_Tree.gif',
    'The brilliant blue spots on this egg stand out.$e197.png',
    'This tiny egg resembles a seed.$e198.png',
    'This shimmering egg was hidden far from the others.$e199.png',
    'This egg’s shell is slippery and clean.$e200.png',
    'Mana flows like a current through this glassy egg.$e208.png',
    'This plain blue egg almost seems to float.$e212.png',
    'This egg shakes slightly when taken out of the light.$e214.png',
    'It feels like this egg knew you were coming.$e222.png',
    'This egg emanates a peculiar smell.$e226.png',
    'This tiny egg flashes in the sunlight.$e227.png',
    'This tiny white egg shakes sometimes.$e228.png',
    'This egg is surrounded by beautiful flowers.$e229.png',
    'This egg has spots that glow brightly when touched.$e231.png',
    'This pleasant egg was placed in the path of a refreshing breeze.$dc_16th_birthday_4.png',
    'This tiny blue egg gives you a slight shock when you touch it.$e_202207_1.png',
    'This scaled egg is surrounded by the others.$e_202207_4.png',
    'A single blue spot marks this egg.$e_202208_1.png',
    'Two thin stripes crisscross the shell of this egg.$e_202209_2.png',
    'This egg glows with the light of the moon.$e_202304_1_1.png',
    'A red stone is embedded in this egg’s cold shell.$dc_17th_birthday_3.png',
    'This smooth egg has a bright blue stripe on it.$dc_17th_birthday_6.png',
    'This smooth egg has dark markings.$e_202306_1_3.gif',
    'Delicate petals envelop this egg.$e_202307_1_3.png',
    'This egg is well-camouflaged.$e_202308_1.png',
    'Something about this heavy egg unnerves you.$e_202308_2.png',
    'The light swirls on this egg stand out against the dark underbrush.$e_202310_1.png',
    'This egg seems lonely sitting by itself.$e_202404_1.png',
    'A serene calm washes over you as you approach this navy egg.$dc_18th_birthday_4.png',
    'This dark egg has a delicate shell that smells faintly of pine.$e_202406_1.png',
    'This egg is covered in soft, downy feathers.$e_202407_1.png',
    'Three bold red stripes cut across this egg’s shell.$e_202409_1.png',
    'This egg’s glittering shell sometimes gets lost in fog.$e_202407_2.png',
    'Whenever you pick up this egg, you feel as though someone is watching you.$20250521_ouhou_egg.png',
    'This egg’s shell has thin bands of vivid color.$20250629_lunate_egg.png',
];
const jungle = [
    'This tiny egg is rather light.$e2.png',
    'This heavy egg has a soft, yielding shell.$e4.png',
    'This light egg is floating in the air.$e5.png',
    'This egg has a faint green glow around it.$e8.png',
    'This egg has a pleasant, musky smell.$e9.png',
    'This delicately patterned egg is sitting in the sunshine.$e16.png',
    'This bright egg has a warm shell.$e18.png',
    'This egg is covered in speckles.$e28.png',
    'This mottled red egg almost glows from within.$e31.png',
    'This egg is hidden by some leaves.$e32.png',
    'This pink and red egg wobbles occasionally.$e33.png',
    'This egg makes you feel a bit uneasy.$e34.png',
    'This translucent egg shines like starlight.$e35.png',
    'This egg is soft and smells uncannily like cheese.$e36.png',
    'This egg is much smaller than the others.$e37.png',
    'This egg is so tiny you almost didn’t see it.$e39.png',
    'This egg gleams with a reddish shine.$e42.png',
    'This egg is sitting in a patch of grass and small flowers even though there’s no sun in the cave.$e44.png',
    'This egg shines coldly in the moonlight.$e45.png',
    // 'This tiny egg is mysterious and dark.$e46_20210508.png',
    'This tiny egg is mysterious and dark.$e46.png',
    'This egg is sitting on a cloud.$e47.png',
    'This egg has multiple bands of color on it.$e51.gif',
    'This egg can’t seem to make up its mind what color it is.$e52.png',
    'This mottled egg looks positively ancient.$e56.png',
    'This egg is patterned with an orange flare.$e57.png',
    'It’s bright. And pink.$e61.png',
    'This egg is yellow with orange speckling.$e65.png',
    'This egg is encrusted with colorful gemstones.$e69.png',
    'This tiny egg gives off a colorful glow.$e73.png',
    'This egg is very reflective, almost metallic-looking.$e74.png',
    'This egg is covered in tiny golden scales.$e80.png',
    'This egg has strange markings on it.$e82.gif',
    'A few bright markings decorate this egg’s shell.$e83.png',
    'You hear strange noises coming from inside this egg.$e86.png',
    'This egg is hidden in the trees.$e88.png',
    'This shiny egg gives off an almost magical aura.$e90.png',
    'This tiny cobalt egg has a crystalline sheen.$e92.png',
    'This glowing egg seems to tug at your very core.$e95.png',
    'This egg shines brightly in the sunlight.$e96.png',
    'This egg has an orange aura radiating from it.$e100.png',
    'This tiny glowing egg tempts you to follow its light.$e104.png',
    'This egg is hidden behind the others, as if it is shy.$e105.png',
    'This tiny egg has crazy swirls on it.$e106.png',
    'This egg is buried in leaf litter.$e107.png',
    'This egg looks like it doesn’t belong; it is brightly colored with white spots. It’s much lighter than the other eggs.$e109.gif',
    'This egg has strange yellow stripes.$e111.png',
    'This egg is tiny and made out of several pieces of paper folded together.$e117.png',
    'This little egg is soft with a few feathers stuck to it.$e119.png',
    'This massive egg is covered with thick plates.$e120.png',
    'Wow, purple isn’t a color of egg you expected to see.$e121.png',
    'This tiny egg has a bold red streak on it.$e129.png',
    'This egg radiates an otherworldly chill.$e131.png',
    'This egg looks like a beautiful blue stone.$e134.png',
    'This egg gives off a beautiful glow.$e140.png',
    'This light egg has very vibrant colors.$e143.png',
    'This egg has brightly colored markings on it.$e148.gif',
    'This egg is surrounded by fog.$e150.png',
    'This egg changes colors in the sunlight.$e153.png',
    'This egg has faint markings.$e157.png',
    'This egg is split down the middle into two colors.$e162.png',
    'This egg seems to be floating on a puddle.$e168.png',
    'This egg has a very clean look; it’s completely devoid of dirt and scratches.$e171.png',
    'Mana courses throughout this glassy egg.$e174.gif',
    'This shiny egg seems to radiate power.$e183.png',
    'This egg has a rough shell.$e185.png',
    'This egg has bright orange and green markings.$e186.png',
    'This egg looks like it doesn’t belong; it is brightly colored with white spots.$e59.png',
    'This egg looks like it doesn’t belong; it is brightly colored with white spots. It’s much warmer than the rest of the eggs.$e60.png',
    'This egg looks like it doesn’t belong; it is brightly colored with white spots. It’s much heavier than the other eggs.$e190.png',
    'The vibrant scales on this egg glisten in the sunlight.$e192.png',
    'This egg is very large, but light for its size.$e194.png',
    'The brilliant blue spots on this egg stand out.$e197.png',
    'This tiny egg resembles a seed.$e198.png',
    'This shimmering egg was hidden far from the others.$e199.png',
    'This egg’s shell is slippery and clean.$e200.png',
    'Mana flows like a current through this glassy egg.$e208.png',
    'You hear a soft melody as you approach this egg.$e213.png',
    'This egg shakes slightly when taken out of the light.$e214.png',
    'Something about this egg seems to lure you in.$e215.png',
    'Soft chirping sounds are coming from inside the egg.$e219.png',
    'This shiny egg smells faintly like flowers.$e220.png',
    'It feels like this egg knew you were coming.$e222.png',
    'This egg has a winding pattern on it.$e223.png',
    'This egg emanates a peculiar smell.$e226.png',
    'This tiny egg flashes in the sunlight.$e227.png',
    'This tiny white egg shakes sometimes.$e228.png',
    'This egg has spots that glow brightly when touched.$e231.png',
    'This egg has delicate markings that curl around its shell.$dc_16th_birthday_5.png',
    'This tiny blue egg gives you a slight shock when you touch it.$e_202207_1.png',
    'This scaled egg is surrounded by the others.$e_202207_5.png',
    'A single blue spot marks this egg.$e_202208_1.png',
    'Two thin stripes crisscross the shell of this egg.$e_202209_2.png',
    'This dull mottled egg blends into the surrounding algae.$e_202303_1.png',
    'This egg glows with the light of the moon.$e_202304_1_1.png',
    'Shadows flicker wildly around this diminutive egg.$e_202304_2.png',
    'A red stone is embedded in this egg’s cold shell.$dc_17th_birthday_3.png',
    'This smooth egg has dark markings.$e_202306_1_3.gif',
    'Delicate petals envelop this egg.$e_202307_1_3.png',
    'Something about this heavy egg unnerves you.$e_202308_2.png',
    'The light swirls on this egg stand out against the dark underbrush.$e_202310_1.png',
    'It is difficult to discern this egg from its gloomy surroundings.$e_202310_2.png',
    'This egg seems lonely sitting by itself.$e_202404_1.png',
    'This partially scaled egg looks like it was placed with great care.$dc_18th_birthday_3.png',
    'This egg looks like it doesn’t belong; it is glossy and covered with white spots.$e_202409_2.png',
    'This tiny egg is leathery and damp.$202504_trion_egg.png',
    'This tiny egg is cold and clammy.$20250521_gloomstalker_egg.png',
    'This egg is carefully nestled away in soft grasses and feathers.$20250629_crested_egg.png',
];
const volcano = [
    'This tiny egg is rather light.$e2.png',
    'This egg has a faint green glow around it.$e8.png',
    'This egg has a pleasant, musky smell.$e9.png',
    'This ashen egg is smooth to the touch.$e19.png',
    'This egg is dark with light speckles...or maybe it’s light with dark speckles?$e22.png',
    'This egg smells rather rancid.$e29.png',
    'This egg makes you feel a bit uneasy.$e34.png',
    'This translucent egg shines like starlight.$e35.png',
    'This egg is soft and smells uncannily like cheese.$e36.png',
    'This egg is much smaller than the others.$e37.png',
    'This egg gleams with a reddish shine.$e40.png',
    'This egg is tiny and brightly colored.$e43.png',
    'This egg shines coldly in the moonlight.$e45.png',
    'This egg shines like a diamond.$e50.png',
    'This egg can’t seem to make up its mind what color it is.$e52.png',
    'This egg is really hot.$e54.png',
    'Cold flames dance across the surface of this egg.$e55.png',
    'This mottled egg looks positively ancient.$e56.png',
    'This rough egg has shimmering veins of crystal running across its surface.$e58.gif',
    'It’s bright. And pink.$e62.png',
    'Powerful energy emanates from this egg.$e67.png',
    'This egg is heavy and rough, as if it were made out of rock.$e70.png',
    'This egg glitters oddly in the light.$e71.png',
    'This egg is very reflective, almost metallic-looking.$e74.png',
    'This egg is sitting in a pile of small pebbles.$e76.png',
    'This egg is sitting in front of the others.$e77.png',
    'This egg radiates the heat of a fell flame.$e79.png',
    'This egg is hidden in the trees.$e88.png',
    'This shiny egg gives off an almost magical aura.$e90.png',
    'This tiny cobalt egg has a crystalline sheen.$e92.png',
    'This red and gold egg sits before the others, almost daring you to grab it.$e94.png',
    'This egg shines brightly in the sunlight.$e96.png',
    'This metallic egg shows faint iridescence in moonlight.$e98.gif',
    'This egg has an orange aura radiating from it.$e100.png',
    'This egg is almost too hot to touch.$e101.png',
    'This egg is hidden behind the others, as if it is shy.$e105.png',
    'This dense, crystalline egg seems dangerously unstable.$e112.png',
    'This egg is tiny and made out of several pieces of paper folded together.$e117.png',
    'This little egg is soft with a few feathers stuck to it.$e119.png',
    'Wow, purple isn’t a color of egg you expected to see.$e121.png',
    'This egg feels like polished stone.$e123.png',
    'This glassy egg is too hot to hold with your bare hands.$e125.png',
    'This egg is rather warm.$e127.png',
    'This egg radiates an otherworldly chill.$e131.png',
    'This large egg is a dark crimson color.$e133.png',
    'This egg looks like a beautiful blue stone.$e134.png',
    'This egg seems quite harmless.$e135.png',
    'This egg is covered in mysterious patterns.$e136.png',
    // 'This plain-looking egg has faint speckles.$e139_20210508.png',
    'This egg has striations marking its rough shell.$e139.png',
    'This egg gives off a beautiful glow.$e140.png',
    'This glassy egg has a single stripe on it.$e145.gif',
    'This egg is surrounded by fog.$e150.png',
    'This egg is split down the middle into two colors.$e162.png',
    'This egg has a very clean look; it’s completely devoid of dirt and scratches.$e171.png',
    'Mana courses throughout this glassy egg.$e176.gif',
    'This shiny egg seems to radiate power.$e184.png',
    'This ashen egg is smooth to the touch.$e19.png',
    'This dull egg feels cozily warm.$e196.png',
    'The brilliant blue spots on this egg stand out.$e197.png',
    'This tiny egg resembles a seed.$e198.png',
    'This shimmering egg was hidden far from the others.$e199.png',
    'Mana flows like a current through this glassy egg.$e208.png',
    'This egg shakes slightly when taken out of the light.$e214.png',
    'Something about this egg seems to lure you in.$e215.png',
    'This egg has a dull metallic luster and is hot to the touch.$e216.png',
    'This shiny gray egg smells of burnt metal.$e218.png',
    'This striped egg is surprisingly heavy.$e221.png',
    'Tough ridges line the surface of this rough, mottled egg.$e225.png',
    'This tiny egg flashes in the sunlight.$e227.png',
    'This tiny white egg shakes sometimes.$e228.png',
    'When you tap on this shell, the hatchling inside taps back.$dc_16th_birthday_6.png',
    'This tiny blue egg gives you a slight shock when you touch it.$e_202207_1.png',
    'This scaled egg is surrounded by the others.$e_202207_7.png',
    'Two thin stripes crisscross the shell of this egg.$e_202209_2.png',
    'This egg glows with the light of the moon.$e_202304_1_1.png',
    'A red stone is embedded in this egg’s cold shell.$dc_17th_birthday_3.png',
    'This dark egg has bright flecks that almost seem to move as they catch the light.$dc_17th_birthday_7.png',
    'This smooth egg has dark markings.$e_202306_1_3.gif',
    'Delicate petals envelop this egg.$e_202307_1_1.png',
    'Something about this heavy egg unnerves you.$e_202308_2.png',
    'It is difficult to discern this egg from its gloomy surroundings.$e_202310_2.png',
    'This egg looks like cooled lava.$e_202403_2.png',
    'This egg seems lonely sitting by itself.$e_202404_1.png',
    'This iridescent egg radiates the warmth of the sun.$dc_18th_birthday_5.png',
    'This heavy egg has a distinct scorched smell.$e_202406_4.png',
    'This egg has a fiery pattern.$20250727_flameback_egg.png',
];
const holiday = [
    // Valentine's Day
    'This egg is speckled and very fragile.$valentine2009.png',
    'This egg looks delicate and sweet.$valentine2010.png',
    'This sweet-smelling egg is covered by a ribbon.$valentine2011.png',
    'This scarlet egg has a faintly sweet aroma.$valentine2012.png',
    'This egg is a deep pink.$valentine2013.png',
    'This radiant white egg has red and gold swirls on it.$valentine2014.png',
    'This egg is so shiny it makes you want to take it.$valentine2015.png',
    'This lovely egg has rolled off to the side.$valentine2016.png',
    'This deep purple egg shimmers like a pearl.$valentine2017.png',
    'This egg has a sweet, floral scent.$valentine2018.png',
    'This warm egg is surrounded by plants.$valentine2019.png',
    'This regal egg feels oddly light.$valentine2020.png',
    'Dim flames spark up from this egg whenever joy sparks up in you.$valentine2021.png',
    'This egg smells pleasantly floral, maybe fruity.$valentine2022.png',
    'Colorful swirls decorate the surface of this glossy egg.$valentine2023.png',
    'Holding this warm egg rekindles your spirit.$valentine2024.png',
    'This egg emits an enchanting glow.$valentine2025.png',
    // Halloween
    'This egg is stone cold and smells rotten.$halloween2008.png',
    'This egg smells like the autumn harvest.$halloween2009.png',
    'This egg is covered in a dark crust.$halloween2010.png',
    'This egg fades into the shadows.$halloween2011.png',
    'This egg is wedged in a dark corner.$halloween2012.png',
    'This egg appears to have an evil grin.$halloween2013.png',
    'Being near this egg makes it hard to think clearly.$halloween2014.png',
    'The pattern on this egg’s shell is unsettling.$halloween2015.png',
    'This downy egg is hidden in brambles.$halloween2016.png',
    'This warm egg is tangled in the roots of a dead tree.$halloween2017.png',
    'This egg has reflective spots that remind you of gems, or eyes.$halloween2018.png',
    'A fine mist rolls over this cool, scaly egg.$halloween2019.png',
    'Dead leaves obscure this egg’s scratched shell.$halloween2020.png',
    'Your eyes struggle to completely focus on the light coming through this cloudy egg.$halloween2021.png',
    'This cool, weathered egg is a heavy burden to bear.$halloween2022.png',
    'Soft bioluminescence shifts over the surface of this dark egg.$halloween2023.png',
    // Christmas
    'This egg has a holly leaf stuck to it.$christmas2007.png',
    'This egg is covered with bright, festive stripes.$christmas2008.png',
    'This egg fills you with holiday cheer.$christmas2009.png',
    'This egg shines like a holiday ribbon.$christmas2010.png',
    // 'This colorful egg is covered by a light layer of snow.$christmas2011_20210508.png',
    'This colorful egg is covered by a light layer of snow.$christmas2011.png',
    'This egg has a rich, shiny pattern on it.$christmas2012.png',
    'This egg emits a soft, heartwarming glow.$christmas2013.png',
    'This colorful egg gleams in the light.$christmas2014.png',
    'A wintry chill swirls just beneath the surface of this egg.$christmas2015.png',
    'This egg is surrounded by frost.$christmas2016.png',
    'This festive egg gives off comforting warmth.$christmas2017.png',
    'This egg glows with a soft, soothing light.$christmas2018.png',
    'This egg emanates a gentle chime when met with the winter breeze.$christmas2019.png',
    'Colorful light twinkles within this frozen egg.$christmas2020.png',
    'This warm brown egg smells faintly of spices.$christmas2021.png',
    'A warm, comforting light emanates from within this egg.$christmas2022.png',
    'Powdery snow swirls gently around this egg.$christmas2023.png',
];

const biomes = {
    1: coast,
    2: desert,
    3: forest,
    4: jungle,
    5: alpine,
    6: volcano,
    7: holiday
};

export default biomes;
