const SILVER = 'rgb(185,220,235)'; // Uncommon
const GOLD   = 'rgb(230,205,140)'; // Rare
const RED    = 'rgb(245,145,5)';   // Mythic Rare

const RARITY = {
	'e11.png':  { 'rarity': 'Rare', },
	'e25.png':  { 'rarity': 'Rare', },
	'e36.png':  { 'rarity': 'Mythic Rare', },
	'e37.png':  { 'rarity': 'Mythic Rare', },
	'e40.png':  { 'rarity': 'Mythic Rare', },
	'e41.png':  { 'rarity': 'Mythic Rare', },
	'e42.png':  { 'rarity': 'Mythic Rare', },
	'e58.gif':  { 'rarity': 'Uncommon', },
	'e59.png':  { 'rarity': 'Mythic Rare', },
	'e60.png':  { 'rarity': 'Mythic Rare', },
	'e74.png':  { 'rarity': 'Mythic Rare', },
	'e87.png':  { 'rarity': 'Rare', },
	'e101.png': { 'rarity': 'Rare', },
	'e109.gif': { 'rarity': 'Mythic Rare', },
	'e117.png': { 'rarity': 'Mythic Rare', },
	'e122.png': { 'rarity': 'Uncommon', },
	'e123.png': { 'rarity': 'Uncommon', },
	'e124.png': { 'rarity': 'Uncommon', },
	'e140.png': { 'rarity': 'Mythic Rare', },
	'e158.png': { 'rarity': 'Rare', },
	'e172.gif': { 'rarity': 'Rare', },
	'e173.gif': { 'rarity': 'Rare', },
	'e174.gif': { 'rarity': 'Rare', },
	'e175.gif': { 'rarity': 'Rare', },
	'e176.gif': { 'rarity': 'Rare', },
	'e177.gif': { 'rarity': 'Rare', },
	'e179.png': { 'rarity': 'Uncommon', },
	'e180.png': { 'rarity': 'Uncommon', },
	'e181.png': { 'rarity': 'Uncommon', },
	'e182.png': { 'rarity': 'Uncommon', },
	'e183.png': { 'rarity': 'Uncommon', },
	'e184.png': { 'rarity': 'Uncommon', },
	'e187.png': { 'rarity': 'Rare', },
	'e190.png': { 'rarity': 'Mythic Rare', },
	'e208.png': { 'rarity': 'Rare', },
	'Leetle_Tree.gif': { 'rarity': 'Rare', },
}
